import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import React from "react";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme/MuiTheme";

import StoreProvide from "@/service/StoreProvide";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider options={{ key: "css", enableCssLayer: true }}>
          <StoreProvide>
            <ThemeProvider theme={theme}>{children}</ThemeProvider>
          </StoreProvide>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
